version: '3.10'

volumes:
  dbdata:

networks:
  localhost:
    driver: bridge

services:
  api:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/home/snappy_user/snappy_app
    env_file: .env
    container_name: snappy-app-container
    depends_on:
      - db
    links:
      - db
    networks:
      - localhost

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: snappy-tool-db
    ports:
      - 5433:5432
    volumes:
      - dbdata:/var/lib/postgresql
    networks:
      - localhost
